server:
 port: 8080
 
spring:
 application:
  name: api-gateway
    
 #profiles:
  #active:
   #- dev
   
 main:
  web-application-type: reactive
    
 cloud:
  gateway:
   default-filters:
    - RemoveRequestHeader=Cookie
   server:
    webflux:
     routes:
      - id: store-command
        uri: lb://store-command
        predicates:
         - Path=/store-command/**
        filters:
         - StripPrefix=1
      - id: store-query
        uri: lb://store-query
        predicates: 
         - Path=/store-query/**
        filters:
         - StripPrefix=1
       
 #OAuth2 COnfiguration http://localhost:9090/realms/Bouzar/.well-known/openid-configuration
 security:
  oauth2:
   resourceserver:
    jwt: 
     issuer-uri: http://localhost:9090/realms/Bouzar
     jwk-set-uri: http://localhost:9090/realms/Bouzar/protocol/openid-connect/certs
    
eureka:
 client:
  service-url:
   defaultZone: http://localhost:8761/eureka/   

logging:
 level:
  org.springframework.cloud.gateway: INFO
  org.springframework.security: INFO

#Expose the endpoint from the actuator
management:
 endpoints:
  web:
   exposure:
    include: health, info
 endpoint:
  gateway:
   enabled: true
 security:
  enabled: false
    
  


        

