server:
 port: 8082
 
spring:
 application:
  name: store-query
 
 profiles:
   active:
    - dev

 datasource:
    url: jdbc:mysql://localhost:3306/productquerydb
    username: root
    password: password
    driver-class-name:
     com.mysql.cj.jdbc.Driver
   
 jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        format_sql: true
 #OAuth2 COnfiguration http://localhost:9090/realms/Bouzar/.well-known/openid-configuration
 security:
  oauth2:
   resourceserver:
    jwt: 
     issuer-uri: http://localhost:9090/realms/Bouzar
  
 kafka:
  template:
   default-topic: pro-topic1
  consumer:
   bootstrap-servers: localhost:9092
   group-id: pro-group1
   auto-offset-reset: earliest
   key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
   value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      
  #Kafka can deserialize all the classes from this package
  properties:
   spring:
    json:
     trusted:
      packages: com.cqsr.event
      
logging:
 level:
  com.miaoubich: INFO
      
eureka:
 client:
  service-url:
   defaultZone: http://localhost:8761/eureka/
