server:
 port: 8081
spring:
  profiles:
   active:
    - dev
  application:
    name: store-command

  datasource:
    url: jdbc:mysql://localhost:3306/productcmddb
    username: root
    password: password
    driver-class-name: com.mysql.cj.jdbc.Driver

    
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        format_sql: true
        
 
  kafka:
    template:
      default-topic: pro-topic1
    producer:
      bootstrap-servers: localhost:9092
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer

logging:
 level:
  com.miaoubich: INFO

