server:
 port: 8083
spring:
  application:
    name: order-service
    
  #profiles:
   #active:
    #- dev

  datasource:
    url: jdbc:mysql://localhost:3306/orderdb
    username: root
    password: password
    driver-class-name: com.mysql.cj.jdbc.Driver
    
 #OAuth2 COnfiguration http://localhost:9090/realms/Bouzar/.well-known/openid-configuration    
  security:
   oauth2:
    resourceserver:
     jwt:
      issuer-uri: http://localhost:9090/realms/Bouzar

    
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        format_sql: true
        
 
  kafka:
    template:
      default-topic: pro-topic1
    producer:
      bootstrap-servers: localhost:9092
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer

logging:
 level:
  com.miaoubich: INFO
  
eureka:
 client:
  service-url:
   defaultZone: http://localhost:8761/eureka/


