server:
 port: 8083
spring:
  profiles:
   active:
    - dev
  application:
    name: security

  datasource:
    url: jdbc:mysql://localhost:3306/jwt_securitydb
    username: root
    password: password
    driver-class-name: com.mysql.cj.jdbc.Driver

    
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        format_sql: true
        
#to generate new key run 'openssl rand -base64 32' in git bash 
secret:
 key: 1cRp2mws9Oly4LgGjH4MTAbQLbGl4zEe8p7lK2Jd5Sw=

